### ISSUE TITLE
Database Table

### ISSUE THREAD

**Issue by simplethemes** [imarc/craft-dbsessions#1]
Hi, thanks for sharing this.
Is the dbsessions_sessions table supposed to be created automatically?

I'm getting the following error:

> Base table or view not found: 1146 Table 'infodev_cms.dbsessions_sessions' doesn't exist

**Comment by marcuswindecker** [comment]
@simplethemes I was wondering if you were able to solve this issue. My coworker is seeing the same issue, but it worked perfectly for me when first configuring the plugin.

**Comment by jeffturcotte** [comment]
@marcuswindecker (...and sorry for the late comment @simplethemes)

The database table is **supposed** to by created automatically. [See code here.](https://github.com/imarc/craft-dbsessions/blob/master/SessionHandler.php#L62)

That is all baked into Craft's (or Yii's) caching libs and I don't know too much about how it's working behind the scenes. My first guess is that you have restrictive db permissions (intentional or not) that might limit `CREATE` statements from whatever db user you connect as.

I added a blurb to the [README's usage section](https://github.com/imarc/craft-dbsessions/blob/master/README.md#usage) with the SQL to create the table manually if it comes to that, but I recommend reviewing your db perms as well. 

Best.

**Comment by marcuswindecker** [comment]
Thanks @jeffturcotte!
